version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: AtomDev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    networks:
      - vtz-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Используем имя сервиса db, чтобы приложение могло подключиться по сети docker-compose
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/AtomDev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "80:8080"
    networks:
      - vtz-network

networks:
  vtz-network:
    driver: bridge